[package]
name = "Pyth"
version = "0.0.1"
upgrade_policy = "compatible"

[dependencies]
# TODO: pin versions before mainnet release
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "985f19d40457a5f09f2d741b1feca6bf7ba1f8a6" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "6d375306122da45a38eb9a6c95625ce2b7f64cbc" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "6d375306122da45a38eb9a6c95625ce2b7f64cbc" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token/", rev = "985f19d40457a5f09f2d741b1feca6bf7ba1f8a6" }
Wormhole = { git = "https://github.com/ThalaLabs/wormhole.git", subdir = "aptos/wormhole", rev = "aptos/integration" }
Deployer = { git = "https://github.com/ThalaLabs/wormhole.git", subdir = "aptos/deployer", rev = "aptos/integration" }

[addresses]
# These are testnet addresses. source: https://docs.pyth.network/consume-data/aptos
pyth = "0xa1c1e6ec8eca84d93d0c0d2708b840c16895389e6e55c31a6447c97c9257d069"
deployer = "0xb31e712b26fd295357355f6845e77c888298636609e93bc9b05f0f604049f434"
wormhole = "0xaf4faf174bad7dba8092fc5ac37b9b8fea3929f05fcb0677fd16dc735bc3ffc8"
